version: '3.8'

services:
  # Gunicorn + FastAPI
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/${DB_NAME}
      - APP_ENV=production
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - backend
      - frontend

  # PostgreSQL
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # Nginx
  nginx:
    image: nginx:1.23
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  postgres_data:
  static_volume: